version: "2.4"
volumes:
    cmdbuild-db:
    cmdbuild-tomcat:

services:
    cmdbuild_db:
        image: itmicus/cmdbuild:db-3.0
        container_name: cmdbuild_db
        volumes:
            - cmdbuild-db:/var/lib/postgresql/data
        # ports:
        #     - 5432:5432
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
        restart: always
        mem_limit: 1000m
        mem_reservation: 300m

    cmdbuild_app:
        image: itmicus/cmdbuild:r2u-2.0-3.2.1
        container_name: cmdbuild_app
        links:
           - cmdbuild_db
        depends_on:
           - cmdbuild_db
        ports:
            - 8090:8080
        restart: always
        volumes:
            - cmdbuild-tomcat:/usr/local/tomcat
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_PORT=5432
            - POSTGRES_HOST=cmdbuild_db
            - POSTGRES_DB=cmdbuild_r2u2
            - CMDBUILD_DUMP=demo.dump.xz
            - JAVA_OPTS=-Xmx4000m -Xms2000m
        mem_limit: 4000m
        mem_reservation: 2000m